version: '3'

services:
  api:
    build: .
    image: flask-template-api:0.0.1
    container_name: flask-template-api
    restart: always
    ports:
      - 5000:5000
  postgres:
    image: postgres:11
    container_name: flask-template-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
        POSTGRES_DB: template_db
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:5.0.6
    container_name: flask-template-redis
    restart: always
    command: redis-server --requirepass password
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data